spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zheye?characterEncoding=utf-8
    username: root
    password: evostar2020
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 1s
      read-timeout: 30s


mybatis:
  type-aliases-package: com.evostar.model
  mapper-locations: mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8888
  servlet:
    context-path: /api

